
//参考https://portrait.gitee.com/sea_captain/esp32_-cdc_4-g/blob/master/sdkconfig.old的数据来设置

#define CONFIG_MODEM_TARGET_NAME  "AIR724UG-NFM"
#define CONFIG_MODEM_USB_IN_EP_ADDR 0x81
#define CONFIG_MODEM_USB_OUT_EP_ADDR 0x84

#define CONFIG_CDC_BULK_OUT_URB_NUM 1
#define CONFIG_CDC_BULK_IN_URB_NUM 1

#define CONFIG_USBH_TASK_BASE_PRIORITY 1
#define CONFIG_USBH_TASK_CORE_ID 0

#define CONFIG_CDC_BULK_OUT_URB_BUFFER_SIZE 256
#define CONFIG_CDC_BULK_IN_URB_BUFFER_SIZE 256

#define IOT_USBH_CDC_VER_MAJOR 3
#define IOT_USBH_CDC_VER_MINOR 1
#define IOT_USBH_CDC_VER_PATCH 1

#define CONFIG_MODEM_RESET_GPIO 5
#define CONFIG_MODEM_POWER_GPIO 13
#define CONFIG_MODEM_RESET_GPIO_INACTIVE_LEVEL 33
#define CONFIG_MODEM_POWER_GPIO_INACTIVE_LEVEL 33

#define CONFIG_MODEM_PPP_APN "CMNET"
#define CONFIG_MODEM_DIAL_RETRY_TIMES 3

#define IOT_USBH_MODEM_VER_MAJOR 1
#define IOT_USBH_MODEM_VER_MINOR 3
#define IOT_USBH_MODEM_VER_PATCH 3
#define CONFIG_MODEM_SIM_PIN_PWD 3

#define CONFIG_EXAMPLE_WEB_MOUNT_POINT 3
#define CONFIG_MODEM_WIFI_DEFAULT_DNS "8.8.8.8"
#define CONFIG_EXAMPLE_WEB_PASSWORD "123456"
#define CONFIG_EXAMPLE_WEB_USERNAME "admin"


#define CONFIG_MODEM_WIFI_SSID "mySSID"
#define CONFIG_MODEM_WIFI_PASSWORD "12345678"
#define CONFIG_MODEM_WIFI_CHANNEL 1
#define CONFIG_MODEM_WIFI_MAX_STA 4


#define CONFIG_EXAMPLE_LED_RED_SYSTEM_GPIO 4
#define CONFIG_EXAMPLE_LED_BLUE_WIFI_GPIO 18
#define CONFIG_EXAMPLE_LED_GREEN_4GMODEM_GPIO 19
// #define CONFIG_EXAMPLE_LED_GREEN_4GMODEM_GPIO 20

#define IOT_USBH_VER_MAJOR 1
#define IOT_USBH_VER_MINOR 1
#define IOT_USBH_VER_PATCH 2
#define HCD_PORT_STATE_NOT_POWERED 1
#define HCD_PIPE_CMD_HALT 1
#define HCD_PIPE_CMD_FLUSH 1
#define HCD_PIPE_CMD_CLEAR 1






